environments: 
  default:
    values:
     - config/default.yaml
  fungible:
    values:
     - config/default.yaml
     - config/fungible.yaml
  dev:
    values:
    - config/default.yaml
    - config/dev.yaml
  goerli:
    values:
     - config/default.yaml
     - config/goerli.yaml
---
helmDefaults:
  kubeContext: gke_direct-pixel-353917_europe-west1_mangata-dev-alpha
  wait: false

releases:
  - name: anvil
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.anvilEnabled }}
    chart: ../helm-charts/anvil-testnet
    values:
      - environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}

  - name: eigen-aggregator
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.aggregatorEnabled }}
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/aggregator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        configFiles: {{ toYaml .Values.aggregatorConfigFiles | nindent 8 }}
        ethEcdsaKeypairJson: {{ .Values.aggregatorEthEcdsaKeypairJson }}
        ethEcdsaKeypairPassword: {{ .Values.aggregatorEthEcdsaKeypairPassword }}
        env:
          ETH_RPC_URL: {{ .Values.env.ETH_RPC_URL | fetchSecretValue | quote }}
          ETH_WS_URL: {{ .Values.env.ETH_WS_URL | fetchSecretValue | quote }}
          SUBSTRATE_RPC_URL: {{ .Values.env.SUBSTRATE_RPC_URL | quote }}
          CHAIN_ID: {{ .Values.env.CHAIN_ID | quote | squote }}
          BLS_COMPENDIUM_ADDR: {{ .Values.env.BLS_COMPENDIUM_ADDR | quote }}
          BLS_OPERATOR_STATE_RETRIEVER_ADDR: {{ .Values.env.BLS_OPERATOR_STATE_RETRIEVER_ADDR | quote }}
          AVS_SERVICE_MANAGER_ADDR: {{ .Values.env.AVS_SERVICE_MANAGER_ADDR | quote }}
          ECDSA_KEY_FILE: {{ .Values.env.ECDSA_KEY_FILE | quote }}
          AVS_SERVER_IP_PORT_ADDRESS: {{ .Values.env.AVS_SERVER_IP_PORT_ADDRESS | quote }}
          AVS_BLOCK_VALIDATION_PERIOD: {{ .Values.env.AVS_BLOCK_VALIDATION_PERIOD | quote | squote }}
  - name: eigen-operator  
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.operatorEnabled }}
    chart: ../helm-charts/eigen-node
    values:
      - image:
          repository: mangatasolutions/operator
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: {{ .Values.remoteCluster }}
        configFiles: {{ toYaml .Values.operatorConfigFiles | nindent 8 }}
        rpcPort: 9010
        enableServiceMonitorCollectors: {{ .Values.operatorEnableServiceMonitorCollectors }}
        prometheus:
          enabled: true
        env:
          ETH_RPC_URL: {{ .Values.env.ETH_RPC_URL | fetchSecretValue | quote }}
          ETH_WS_URL: {{ .Values.env.ETH_WS_URL | fetchSecretValue | quote }}
          SUBSTRATE_RPC_URL: {{ .Values.env.SUBSTRATE_RPC_URL | quote }}
          CHAIN_ID: {{ .Values.env.CHAIN_ID | quote | squote }}
          BLS_COMPENDIUM_ADDR: {{ .Values.env.BLS_COMPENDIUM_ADDR | quote }}
          BLS_OPERATOR_STATE_RETRIEVER_ADDR: {{ .Values.env.BLS_OPERATOR_STATE_RETRIEVER_ADDR | quote }}
          AVS_SERVICE_MANAGER_ADDR: {{ .Values.env.AVS_SERVICE_MANAGER_ADDR | quote }}
          ECDSA_KEY_FILE: {{ .Values.env.ECDSA_KEY_FILE | quote }}
          BLS_KEY_FILE: {{ .Values.env.BLS_KEY_FILE | quote }}
          AVS_RPC_URL: {{ .Values.env.AVS_RPC_URL | quote }}
          REGISTER_AT_STARTUP: {{ .Values.env.REGISTER_AT_STARTUP | quote | squote }}
  - name: mangata-updater
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.updaterEnabled }}
    chart: ../helm-charts/mangata-updater
    values:
      - image:
          repository: mangatasolutions/mangata-updater
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        walletPrivateKey: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-private-key
        ethChainUrl: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-ethereum-rpc-url
  - name: mangata-sequencer
    namespace: 'eigen-{{ requiredEnv "ENVIRONMENT" }}'
    installed: {{ .Values.sequencerEnabled }}
    chart: ../helm-charts/mangata-sequencer
    values:
      - image:
          repository: mangatasolutions/mangata-sequencer
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        environment: {{ requiredEnv "ENVIRONMENT" | quote }}
        mnemonic: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-sequencer-mnemonic
        ethChainUrl: ref+gcpsecrets://direct-pixel-353917/eigen-mangata-updater-ethereum-rpc-url