apiVersion: v1
kind: Service
metadata:
  name: operator
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9010
  selector:
    app: operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - image: operator
        name: operator
        args:
          - --config 
          - config-files/operator-docker-compose.anvil.yaml
          # - --credible-squaring-deployment 
          # - contracts/script/output/31337/credible_squaring_avs_deployment_output.json
          # - --shared-avs-contracts-deployment 
          # - contracts/script/output/31337/shared_avs_contracts_deployment_output.json
          # - --ecdsa-private-key 
          # - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
        ports:
        - containerPort: 9010      
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
