services:
  sequencer:
    image: mangatasolutions/rollup-sequencer:local
    build: .
    environment:
      MANGATA_URL: ${ROLLUP_SEQUENCER_MANGATA_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ROLLUP_SEQUENCER_ETH_CHAIN_URL:-wss://ethereum.publicnode.com}
      MANGATA_CONTRACT_ADDRESS: "0x5f3f1dbd7b74c6b46e8c44f98792a1daf8d69154"
      MNEMONIC: 'some mnemonic'
