remoteCluster: true

anvilEnabled: false
aggregatorEnabled: true
finalizerEnabled: true
updaterEnabled: false
sequencerEnabled: false

env:
  # rpc
  SUBSTRATE_RPC_URL: wss://collator-02-ws-eigen-mococo.mangata.online
  # contracts
  CHAIN_ID: '"5"'
  AVS_REGISTRY_COORDINATOR_ADDR: 0x5620cDb94BaAaD10c20483bd8705DA711b2Bc0a3
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: '"5"'
  AVS_KICK_PERIOD: '"5"'
  AVS_UPDATE_STAKE_PERIOD: '"10"'
    # OP
  AVS_RPC_URL: https://avs-aggregator-testnet.mangata.online

aggregatorEnvSecrets:
  ECDSA_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-aggregator-ecdsa-key
  ECDSA_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-aggregator-ecdsa-password
  ETH_RPC_URL: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-rpc-url
  ETH_WS_URL: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-ws-url

finalizerEnvSecrets:
  ECDSA_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-operator-1-ecdsa-key
  ECDSA_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-operator-1-ecdsa-password
  BLS_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-operator-1-bls-key
  BLS_KEY_PASSWORD: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-operator-1-bls-password
  ETH_RPC_URL: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-rpc-url
  ETH_WS_URL: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-ws-url
